---
version: "3"
services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - "${PWD}/docker_data/postgresql/data:/var/lib/postgresql/data:delegated"
    ports:
      - 5432:5432
  app:
    build: .
    ports:
      - "4000:4000"
      - "4001:4001"
      - "4021:4021"
  prometheus:
    image: prom/prometheus:latest
    user: root
    volumes:
      - "${PWD}/docker_config/prometheus/etc:/etc/prometheus/"
      - "${PWD}/docker_data/prometheus/data:/prometheus"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:latest
    user: root
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
