---
version: "3"
services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - "${PWD}/docker_data/postgresql/data:/var/lib/postgresql/data:delegated"
    ports:
      - 5432:5432
  app:
    build: .
    ports:
      - "4000:4000"
      - "4001:4001"
